"""adds deleted field to product

Revision ID: 6002632f23d2
Revises: 45bbfd33563d
Create Date: 2019-05-02 13:18:00.664571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6002632f23d2'
down_revision = 'bcbe66c3bc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'deleted')
    # ### end Alembic commands ###
