"""empty message

Revision ID: 650307b7eb89
Revises: 92b4618d8935
Create Date: 2019-02-02 18:55:41.139903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650307b7eb89'
down_revision = '92b4618d8935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
