"""adding product prices

Revision ID: 6d14b34423c7
Revises: 54d83765d73f
Create Date: 2019-02-22 12:24:20.372028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d14b34423c7'
down_revision = '54d83765d73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('selling_price_adult', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('selling_price_baby', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('selling_price_child', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('stock_price_adult', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('stock_price_baby', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('stock_price_child', sa.Float(precision=2), nullable=True))
    op.drop_column('product', 'stock_price')
    op.drop_column('product', 'selling_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('selling_price', sa.FLOAT(), nullable=True))
    op.add_column('product', sa.Column('stock_price', sa.FLOAT(), nullable=True))
    op.drop_column('product', 'stock_price_child')
    op.drop_column('product', 'stock_price_baby')
    op.drop_column('product', 'stock_price_adult')
    op.drop_column('product', 'selling_price_child')
    op.drop_column('product', 'selling_price_baby')
    op.drop_column('product', 'selling_price_adult')
    # ### end Alembic commands ###
