"""empty message

Revision ID: ceb494579c6a
Revises: f8e59206aebc
Create Date: 2019-02-05 14:28:54.854031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb494579c6a'
down_revision = 'f8e59206aebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salary', sa.Float(precision=2), nullable=True))
    op.add_column('provider', sa.Column('commission_rate', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salary')
    op.drop_column('provider', 'commission_rate')
    # ### end Alembic commands ###
