"""empty message

Revision ID: d1ff583c140a
Revises: 650307b7eb89
Create Date: 2019-02-02 23:21:54.627116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ff583c140a'
down_revision = '650307b7eb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(['promoter_id', 'user_id'], 'sale', type_='foreignkey')
    op.create_foreign_key(['promoter_id', 'user_id'], 'sale', 'users', ['promoter_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(['promoter_id', 'user_id'], 'sale', type_='foreignkey')
    op.create_foreign_key(['promoter_id', 'user_id'], 'sale', 'promoter', ['promoter_id'], ['promoter_id'])
    # ### end Alembic commands ###
